name: CI
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:   
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build-gradle
      run: gradle build
    - name: Upload Files
      id: upload
      uses: Creepios/sftp-action@v1.0.3
      with:
        host: ${{ secrets.SERVER }}
        port: 22
        username: ${{ secrets.USERCI }}
        password: ${{ secrets.PASSWORDCI }}
        localPath: './build/libs/'
        remotePath: '/home/user_ci/'

  build:
    needs: FTP-Deploy-Action
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        command_timeout: 200m
        script: |
            echo ${{ secrets.PASSWORD }} | sudo systemctl stop bikepacker
            echo ${{ secrets.PASSWORD }} | sudo systemctl start bikepacker
